services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ctf
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: php:7.3.33-alpine3.14
    container_name: php_web
    platform: linux/amd64
    restart: always
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=ctf
    command: docker-php-ext-install mysqli && apache2-foreground

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db'
